jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # キャッシュのクリア
      - name: Clear Jekyll Cache
        run: rm -rf $(bundle show jekyll)/_cache

      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2

      # 実行権限を付与
      - name: Grant execute permission for deploy script
        run: chmod +x deploy.sh

      # シェルスクリプトを実行
      - name: Run deploy script
        run: ./deploy.sh

      # GitHub Pages にプッシュ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # デプロイするディレクトリを指定
